FORMAT: 1A
HOST: http://127.0.0.1:3000

# JSONPlaceholder Task

This task created to finishing task given by Mr. Guf

# Group Posts
Represents post details. 

---
**Post attributes:**

- id `(Number)` : unique identifier. 
- userId `(Number)` : post's author.
- title `(String)` : post's title.
- body `(String)` : post's body.

---


## Post Collection [/posts]

### List All Post [GET]

+ Response 200 (application/json)
    + Attributes (array[Post, Post, Post])
    
### Create a New Post [POST]

+ Request (application/json)

    + Attributes (PostRequest)

+ Response 201 (application/json)

        + Headers
            + Location: /album/5
            
    + Attributes (Post)
            
### Post Based on User Id [GET /posts/{?userId}]

+ Parameters
    + userId (String, optional, `1`) - Specifying the author

+ Response 200 (application/json)

    + Attributes (array[Post, Post])
            

            
## Post [/posts/{postId}]
Single post.

+ Parameters
    + postId (Number, optional, `1`) - Represent the post id.


### Get single post [GET]

+ Response 200 (application/json)

    + Attributes (Post)

### Put request single post [PUT]

+ Request (application/json)

    + Attributes (PostRequest)


+ Response 201 (application/json)

    + Attributes (Post)

### Patch request single post [PATCH]

+ Request (application/json)

    + Attributes (PostRequest)

+ Response 201 (application/json)

    + Attributes (Post)


### Delete single post [DELETE]

+ Response 204 (application/json)

### Get post's comment [GET /comments]

+ Response 200 (application/json)

    + Attributes (array[Comment, Comment, Comment])

## Data Structures

### Post

+ `userId`: 1,
+ `id`: 2,
+ `title`: "Lorem Ipsum",
+ `body`: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat"

### PostRequest

+ `title`: "Lorem Ipsum",
+ `body`: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat"

### Comment

+ `postId`: 1,
+ `id`: 1,
+ `name`: "id labore ex et quam laborum",
+ `email`: "Eliseo@gardner.biz",
+ `body`: "laudantium enim quasi est quidem magnam voluptate ipsam eos\ntempora quo necessitatibus\ndolor quam autem quasi\nreiciendis et nam sapiente accusantium"
